### ISSUE TITLE
Add possibility to choose directory for task assignment

### ISSUE THREAD

**Issue by maximtop** [Hexlet/cli#13]
Usually I work on case-sensitive volume `/Volumes/dev`, while `@hexlet/cli` forces me to use default user home directory `/Users/maximtop/Hexlet/rails`

Please add possibility to specify directory for hexlet assignments

**Comment by corsicanec82** [comment]
In version 1.3.1, the ability to specify a custom directory for programs has been added. The new version has already been published, enjoy using it.

Thanks for your feedback.
