### ISSUE TITLE
Add node version check

### ISSUE THREAD

**Issue by zxvfc** [Hexlet/cli#18]
Now, if version of nodeJS lower then required, utility just throws exception without any information about the reasons of that error. Will be cool to add check of nodeJS version and produce custom error message for that case.

Current error looks:
![image](https://user-images.githubusercontent.com/24701674/128552309-f5ef9c56-3df5-4ab3-ae25-9b265736bc9d.png)

**Comment by corsicanec82** [comment]
Thanks.
This problem has already been resolved. Try the new version 1.2.4.
